services:
  # Backend (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: charis_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      STYLING_SERVICE_URL: http://charis_styling:3300
      STYLING_SERVICE_INTERNAL_TOKEN: ${INTERNAL_API_KEY}

  # Styling Service (DolphJS)
  styling-service:
    container_name: charis_styling
    build:
      context: ./styling-service
      dockerfile: Dockerfile
    command: sh -c "npm run dev:start"
    volumes:
      - ./styling-service:/app
      - /app/node_modules
    ports:
      - "3300:3300"
    env_file:
      - .env
    environment:
      PORT: 3300
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}

  # Job Worker (BullMQ)
  job-worker:
    build:
      context: ./job-worker
      dockerfile: Dockerfile
    container_name: charis_worker
    volumes:
      - ./job-worker:/app
      - /app/node_modules
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: sh -c "npm run dev:watch"
    environment:
      DJANGO_INTERNAL_URL: http://backend:8000
      STYLING_SERVICE_URL: http://charis_styling:3300
      STYLING_SERVICE_INTERNAL_URL: http://charis_styling:3300
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      DATABASE_URL: ${DATABASE_URL}
      UV_THREADPOOL_SIZE: "128"