services:
  # Backend (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: charis_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      STYLING_SERVICE_URL: http://styling-service:3300
      STYLING_SERVICE_INTERNAL_TOKEN: ${INTERNAL_API_KEY}

  # Styling Service (DolphJS)
  styling-service:
    build:
      context: ./styling-service
      dockerfile: Dockerfile
    container_name: charis_styling
    command: sh -c "npm ci && npm run dev:start"
    volumes:
      - ./styling-service:/app
      - /app/node_modules
    ports:
      - "3000:3300"
    env_file:
      - .env
    environment:
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      JWT_SECRET: ${JWT_SECRET}

  # Job Worker (BullMQ)
  job-worker:
    build:
      context: ./job-worker
      dockerfile: Dockerfile
    container_name: charis_worker
    volumes:
      - ./job-worker:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npm ci && npm run dev:watch"
    environment:
      DJANGO_INTERNAL_URL: http://backend:8000
      STYLING_SERVICE_INTERNAL_URL: http://styling-service:3300
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}

  # # Frontend (React + Vite)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: charis_frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"
  #   env_file:
  #     - .env
    #   depends_on:
    #     - backend
    #     - styling-service
